import Navbar from "@/components/navbar";
import Footer from "@/components/Footer";
import "./globals.css";
import "react-date-range/dist/styles.css";
import "react-date-range/dist/theme/default.css";
import { Providers } from "./providers";
import { ProfileDrawerProvider } from "@/context/ProfileDrawerContext";
import TawkToWidget from "@/components/TawkToWidget";

export const metadata = {
  title: "Townson Apartments & Homes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <TawkToWidget />
        <Providers>
          <ProfileDrawerProvider>
            <Navbar />
            {children}
            <Footer />
          </ProfileDrawerProvider>
        </Providers>
      </body>
    </html>
  );
}
